# Google Fonts Import
google_fonts:
  - IBM Plex Sans:400,700
  - Courier Prime:400

title: Peter Salvato
description: Principal Systems Architect | Operationalizing Intuition
url: "https://petersalvato.github.io/petersalvato-constellation"
baseurl: "/petersalvato-constellation"

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
